language: php

php:
  - 7.1

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=richdocuments
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

sudo: true
before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd ../core/apps/richdocuments
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - ../../lib/composer/bin/phpunit --configuration ./phpunit.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - php: 7.1
      env: DB=mysql
    - php: 7.1
      env: DB=pgsql
  fast_finish: true
